### ISSUE TITLE
bioio-nd2 failing to load from large file

### ISSUE THREAD

**Issue by toloudis** [tlambert03/nd2#211]
Hi! If this is spam or redundant please feel free to close.
Does this issue look like anything you've seen before?
https://github.com/bioio-devs/bioio-nd2/issues/12
The first error I see is: 
UserWarning: ND2File file not closed before garbage collection. Please use `with ND2File(...):` context or call `.close()`.

**Comment by tlambert03** [comment]
yes, that's a valid warning (not an error) that can come from nd2 if you create an `ND2File()` instance, but never close it before the object get's deleted.  Let's continue the conversation over in your other repo to see if we can track down the aberrant usage
