### ISSUE TITLE
nd2[legacy] dependency

### ISSUE THREAD

**Issue by c0deizbae** [tlambert03/nd2#76]
Not sure if anyone else encounter this?

* nd2 version: latest
* Python version: 3.8.10
* Operating System: Ubuntu

### Description

When installing `nd2[legacy]` through `pip` outside of `condo` environment, wurlizter fails to install due to the tag `extra`.

### What I Did

```
pip install nd2[legacy]

ERROR: Could not find a version that satisfies the requirement wurlizter; extra == "legacy" (from nd2[legacy]) (from versions: none)
ERROR: No matching distribution found for wurlizter; extra == "legacy" (from nd2[legacy])
```

**Comment by tlambert03** [comment]
ah shoot!  typo!  thanks

**Comment by c0deizbae** [comment]
Didn't notice it was a typo. Submitted a PR.  #79
